version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file transactionprocess.template.yml --s3-bucket sri-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - transactionprocess.template.yml
    - outputSamTemplate.yaml